name: Deploy Laravel App to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, xml, ctype, curl, openssl, pdo, tokenizer, zip, mysql
        coverage: none

    - name: Install Composer dependencies
      run: |
        composer install --no-dev --optimize-autoloader
        cp .env.example .env
        php artisan key:generate

    - name: Set correct permissions
      run: |
        chmod -R 775 storage bootstrap/cache

    - name: Upload to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: netizens-foundation-ftarc5e9bjd9fpep
        slot-name: production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: .
